import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  AddFooter,
  AddMetadataSection,
  AddReportHeader,
  AddSectionTitle,
  AddSummaryCards,
  BuildFileName,
  FormatCurrency,
  FormatDate,
  FormatDateTime,
  FormatLabel,
  FormatNumber,
  GetDashboardSource,
  GetProfessionalTableOptions,
  NormalizeRole,
  PageMargin,
  PdfColors
} from './PdfReportHelpers';

const NormalizePeriod = (period) => String(period || 'daily').trim().toLowerCase();

const GetCoverageRange = (period, startDate, endDate) => {
  if (period === 'custom' && startDate && endDate) {
    return `${FormatDate(startDate)} to ${FormatDate(endDate)}`;
  }

  const now = new Date();
  const normalizedPeriod = NormalizePeriod(period);
  let start;
  let end;

  if (normalizedPeriod === 'yearly') {
    start = new Date(Date.UTC(now.getUTCFullYear(), 0, 1));
    end = new Date(Date.UTC(now.getUTCFullYear() + 1, 0, 1));
  } else if (normalizedPeriod === 'monthly') {
    start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
    end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1));
  } else {
    start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
    end = new Date(start);
    end.setUTCDate(start.getUTCDate() + 1);
  }

  return `${FormatDate(start)} to ${FormatDate(new Date(end.getTime() - 1))}`;
};

export function ExportFinancialReportPdf(report = {}, period = 'daily', role = 'Admin', options = {}) {
  const doc = new jsPDF();
  const generatedBy = NormalizeRole(role);
  const reportPeriod = options.period || report.period || period;
  const normalizedPeriod = NormalizePeriod(reportPeriod);
  const isCustomRange = normalizedPeriod === 'custom';
  const periodLabel = isCustomRange ? 'Custom Date Range' : FormatLabel(reportPeriod);
  const fromDate = options.startDate || report.startDate || report.StartDate || '';
  const toDate = options.endDate || report.endDate || report.EndDate || '';
  const generatedDate = FormatDateTime(new Date());
  const coverageRange = GetCoverageRange(normalizedPeriod, fromDate, toDate);
  const invoiceCount = Number(report.count ?? report.invoiceCount ?? report.InvoiceCount ?? 0);
  const totalRevenue = Number(report.revenue ?? report.totalRevenue ?? report.TotalRevenue ?? 0);
  const averageInvoiceValue = invoiceCount > 0 ? totalRevenue / invoiceCount : 0;

  let nextY = AddReportHeader(doc, `${generatedBy} Financial Report`);

  const metadataRows = isCustomRange
    ? [
        ['Report Type', 'Custom Date Range'],
        ['From Date', FormatDate(fromDate)],
        ['To Date', FormatDate(toDate)],
        ['Generated Date', generatedDate],
        ['Generated By', generatedBy]
      ]
    : [
        ['Report Type', 'Financial Revenue Report'],
        ['Period', periodLabel],
        ['Generated Date', generatedDate],
        ['Generated By', generatedBy],
        ['Coverage Range', coverageRange]
      ];

  nextY = AddMetadataSection(doc, metadataRows, nextY);

  nextY = AddSectionTitle(doc, 'Summary Section', nextY);
  nextY = AddSummaryCards(doc, [
    {
      label: 'Total Sale Invoices',
      value: FormatNumber(invoiceCount)
    },
    {
      label: 'Total Revenue',
      value: FormatCurrency(totalRevenue)
    },
    {
      label: 'Average Invoice Value',
      value: FormatCurrency(averageInvoiceValue)
    }
  ], nextY);

  nextY = AddSectionTitle(doc, 'Table Section', nextY);

  const tableRows = [
    ['Report Period', periodLabel],
    ['Date Range', coverageRange],
    ['Sale Invoice Count', FormatNumber(invoiceCount)],
    ['Total Revenue', FormatCurrency(totalRevenue)],
    ['Average Invoice Value', FormatCurrency(averageInvoiceValue)]
  ];

  autoTable(doc, GetProfessionalTableOptions({
    startY: nextY,
    head: [['Metric', 'Value']],
    body: tableRows,
    columnStyles: {
      0: {
        cellWidth: 80,
        fontStyle: 'bold'
      },
      1: {
        cellWidth: 102
      }
    },
    didParseCell: (data) => {
      if (
        data.section === 'body' &&
        data.column.index === 1 &&
        ['Total Revenue', 'Average Invoice Value'].includes(data.row.raw?.[0])
      ) {
        data.cell.styles.halign = 'right';
        data.cell.styles.fontStyle = 'bold';
      }
    }
  }));

  const noteY = (doc.lastAutoTable?.finalY || nextY) + 10;
  if (noteY < doc.internal.pageSize.getHeight() - PageMargin.bottom - 12) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...PdfColors.muted);
    doc.text(
      'Note: This report is generated from sale invoices only. Purchase invoices are excluded from revenue totals.',
      PageMargin.left,
      noteY,
      { maxWidth: doc.internal.pageSize.getWidth() - PageMargin.left - PageMargin.right }
    );
  }

  AddFooter(doc, `Generated from ${GetDashboardSource(generatedBy)} | VPMS Dashboard`);
  const fileName = isCustomRange && fromDate && toDate
    ? BuildFileName('financial-report', fromDate, 'to', toDate)
    : BuildFileName(generatedBy, normalizedPeriod, 'financial-report');
  doc.save(fileName);
}
